source-file ~/.config/tmux/conf.d/00-core.conf
source-file ~/.config/tmux/conf.d/10-navigation.conf
source-file ~/.config/tmux/conf.d/20-copy-paste.conf
source-file ~/.config/tmux/conf.d/30-plugins.conf
source-file ~/.config/tmux/conf.d/40-theme-dracula.conf
source-file ~/.config/tmux/conf.d/50-misc.conf
source-file ~/.config/tmux/conf.d/99-tpm.conf
