# Copy-mode and clipboard.
bind [ copy-mode
bind ] paste-buffer
bind Space choose-buffer

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X rectangle-toggle
# y yank is handled by tmux-yank plugin (see 30-plugins.conf)
