set -g @plugin "~/.config/tmux/plugins/tpm"
set -g @plugin "~/.config/tmux/plugins/tmux-sensible"
set -g @plugin "~/.config/tmux/plugins/tmux-yank"
set -g @plugin "~/.config/tmux/plugins/vim-tmux-navigator"
set -g @plugin "~/.config/tmux/plugins/dracula-pro-tmux"

# Use system clipboard for tmux-yank.
set -g @yank_selection_mouse "clipboard"
